# Generated by Django 6.0.2 on 2026-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('Cancelado', 'cancelado')], default='pendiente', max_length=20),
        ),
    ]
